apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  #ttlSecondsAfterFinished: 100
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-cronjob-container
            image: ubuntu
            #command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
            command:
            - "/bin/bash"
            - "-c"
            - "/bin/echo Hellow from pod-job ${hostname} a las ${date}"
          restartPolicy: Never
