apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  #ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: hello-job-container
        image: ubuntu
        #command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        command:
        - "/bin/bash"
        - "-c"
        - "/bin/echo Hellow from pod-job ${hostname} a las ${date}"
      restartPolicy: Never
