apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/hermes/Documents/capacitacion/microservicios/devops-microservicios/ecosistema-jenkins/k8s-data