spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_SVC_SERVICE_HOST}:${DATABASE_SVC_SERVICE_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: microservicio-service-two
  profiles: qa

server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.1.6:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true

