spring:
  datasource:
    url: jdbc:postgresql://192.168.1.6:5433/microservicio
    username: postgres
    password: project123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: microservicio-service
  profiles: qa

server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.1.6:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true

